name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  markdown_widget:
    path: ../
  cupertino_icons: ^1.0.5
  flutter_test:
    sdk: flutter
  flutter_redux: ^0.10.0
  #html tag parser
  html: ^0.15.0
  #math equation rendering
  flutter_math_fork: ^0.6.3+1

  # for 'video' tag
  video_player: ^2.4.10
  # for router
  go_router: ^6.2.0

dev_dependencies:
  http: ^0.13.5

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/script_medias/