name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  markdown_widget:
    path: ../
  cupertino_icons: ^1.0.5
  flutter_test:
    sdk: flutter
  flutter_redux: ^0.10.0
  #html tag parser
  html: ^0.15.4
  #math equation rendering
  flutter_math_fork: ^0.7.3

  # for 'video' tag
  video_player: ^2.7.2
  # for router
  go_router: ^6.2.0
  # for complex table
  flutter_widget_from_html_core: ^0.15.2

dev_dependencies:
  http: ^0.13.5

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/script_medias/