name: markdown_widget
description: A new markdown package. It supports TOC function, HTML video and img tagï¼Œand it works well on both the web and mobile
version: 1.2.2
verified publisher:
  - agedchen@gmail.com
homepage: https://github.com/asjqkkkk/markdown_widget

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #markdown data parser
  markdown: ^2.1.5

  #highlight code
  highlight: ^0.6.0
  flutter_highlight: ^0.6.0

  #html tag parser
  html: ^0.14.0+3

  # for 'video' tag
  video_player_web: ^0.1.2+1
  video_player: ^0.10.5
  chewie: ^0.9.10

  # for TOC
  scrollable_positioned_list: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
